<?php

namespace App\View\ViewModels;

class ProductViewModel
{
    /**
     * Get all mock products for catalog listing.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            [
                'id' => 1,
                'slug' => 'blue-mind',
                'sku' => 'BZ-MND-001',
                'barcode' => '628100091001',
                'name_en' => 'BLUE MIND',
                'name_ar' => 'بلو مايند',
                'tagline_en' => 'Daily Cognitive & Nootropic Support',
                'tagline_ar' => 'دعم إدراكي وتركيز عصبي يومي متطور',
                'category_en' => 'Cognitive & Brain Health',
                'category_ar' => 'صحة الدماغ والإدراك',
                'subcategory_en' => 'Nootropics',
                'subcategory_ar' => 'منشطات الذهن الطبيعية',
                'brand' => 'Blue Zone Bioceuticals',
                'price' => 68.00,
                'sale_price' => 58.00,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => false,
                'status' => 'active',
                'rating' => 4.9,
                'reviews_count' => 142,
                'image' => '/assets/products/blue-mind.jpg',
                'images' => [
                    '/assets/products/blue-mind.jpg',
                    '/assets/products/blue-cell.jpg',
                ],
                'stock_online' => 124,
                'stock_offline' => 38,
                'low_stock_threshold' => 15,
                'short_description_en' => 'Precision-engineered nootropic complex supporting synaptic plasticity, memory recall, and sustained cerebral focus without jitters.',
                'short_description_ar' => 'مركب نوتروبيك عالي الدقة يدعم مرونة المشابك العصبية، سرعة الاسترجاع الذهني، والتركيز المتواصل دون توتر.',
                'description_en' => 'Inspired by the cognitive longevity of Ikarian and Okinawan centenarians, BLUE MIND synergizes pharmaceutical-grade bio-lipids with standardized plant adaptogens. It modulates acetylcholine synthesis while shielding neuronal mitochondria from oxidative degradation.',
                'description_ar' => 'مستوحى من طول العمر الإدراكي لدى كبار السن في إيكاريا وأوكيناوا. يجمع بلو مايند بين الدهون الحيوية ذات الجودة الصيدلانية ومضادات الأكسدة النباتية الموحدة لتحفيز الأستيل كولين وحماية الميتوكوندريا العصبية.',
                'benefits_en' => [
                    'Sustained mental stamina for 8+ hours without caffeine crash',
                    'Supports neurogenesis and BDNF (Brain-Derived Neurotrophic Factor) signaling',
                    'Clinically studied dosages for verbal fluency and working memory',
                    'Shields neural micro-vessels with targeted bioflavonoids',
                ],
                'benefits_ar' => [
                    'طاقة ذهنية متواصلة لأكثر من 8 ساعات دون هبوط أو كافيين',
                    'يدعم تجدد الخلايا العصبية وإشارات عامل التغذية العصبية BDNF',
                    'جرعات مدروسة سريرياً لتحسين الطلاقة اللغوية والذاكرة العاملة',
                    'حماية الأوعية الدموية الدقيقة في الدماغ بالبيوفلافونويد المنقى',
                ],
                'usage_en' => 'Take 2 capsules every morning with 250ml of mineral water, preferably alongside a healthy fat source such as cold-pressed extra virgin olive oil.',
                'usage_ar' => 'تناول كبسولتين كل صباح مع 250 مل من الماء النقي، يفضل مع مصدر دهون صحية كزيت الزيتون البكر الممتاز المعصور على البارد.',
                'dosage_en' => '2 Veg Capsules Daily',
                'dosage_ar' => 'كبسولتان نباتيتان يومياً',
                'package_size_en' => '60 Vegetable Capsules (30-day supply)',
                'package_size_ar' => '60 كبسولة نباتية (تكفي 30 يوماً)',
                'target_audience_en' => 'Professionals, biohackers, and individuals seeking lifelong cognitive resilience.',
                'target_audience_ar' => 'المحترفون، ورواد الصحة الخلوية، ومن يتطلعون لمرونة إدراكية ممتدة مدى الحياة.',
                'gender' => 'Unisex',
                'age_group' => '18+',
                'health_goal_en' => 'Cognition, Mental Clarity, Focus',
                'health_goal_ar' => 'التركيز، الصفاء الذهني، والذاكرة',
                'professional_info' => [
                    'clinical_mechanism' => 'Choline donor phosphatidylcholine combined with phospholipid-bound serine promotes synaptic vesicle docking. Ginkgo flavonoids enhance cerebral microcirculation and oxygen perfusion rate.',
                    'formula_details' => 'Standardized Ginkgo Biloba (24% flavone glycosides, 6% terpene lactones), Phosphatidylserine 20% soy-free sunflower lecithin, Ubiquinol CoQ10 99.5% pure Kaneka bio-fermented.',
                    'contraindications' => 'Patients taking anticoagulants (warfarin, heparin) or MAO inhibitors must consult their supervising physician prior to administration due to vasodilation properties.',
                    'warnings' => 'Keep out of reach of children. Store in a cool dry dark place below 25°C. Do not exceed recommended daily threshold without clinical blood panel supervision.',
                    'interactions' => 'Synergistic with Omega-3 DHA/EPA. Mild antagonism with high-dose cholinergic antagonists.',
                ],
                'ingredients' => [
                    ['name_en' => 'Ginkgo Biloba Extract (50:1)', 'name_ar' => 'مستخلص الجنكة بيلوبا (50:1)', 'dose' => '120 mg'],
                    ['name_en' => 'Phosphatidylserine (Sunflower)', 'name_ar' => 'فوسفاتيديل سيرين (دوار الشمس)', 'dose' => '100 mg'],
                    ['name_en' => 'Phosphatidylcholine', 'name_ar' => 'فوسفاتيديل كولين', 'dose' => '150 mg'],
                    ['name_en' => 'Kaneka Ubiquinol (CoQ10)', 'name_ar' => 'يوبيكوينول كانيكا المنقى', 'dose' => '100 mg'],
                    ['name_en' => 'Setria L-Glutathione', 'name_ar' => 'إل-جلوتاثيون نقي', 'dose' => '50 mg'],
                ],
                'variants' => [
                    [
                        'id' => 101,
                        'name_en' => 'Standard 30-Day Protocol (60 Capsules)',
                        'name_ar' => 'بروتوكول 30 يوماً القياسي (60 كبسولة)',
                        'sku' => 'BZ-MND-60C',
                        'price' => 68.00,
                        'stock_online' => 84,
                        'stock_offline' => 24,
                    ],
                    [
                        'id' => 102,
                        'name_en' => 'Longevity 90-Day Protocol (180 Capsules)',
                        'name_ar' => 'بروتوكول طول العمر 90 يوماً (180 كبسولة)',
                        'sku' => 'BZ-MND-180C',
                        'price' => 174.00,
                        'stock_online' => 40,
                        'stock_offline' => 14,
                    ],
                ],
            ],
            [
                'id' => 2,
                'slug' => 'blue-cell',
                'sku' => 'BZ-CEL-002',
                'barcode' => '628100091002',
                'name_en' => 'BLUE CELL',
                'name_ar' => 'بلو سيل',
                'tagline_en' => 'Cellular Longevity & Mitochondrial Bio-Shield',
                'tagline_ar' => 'تجديد الخلايا والدرع الحيوي للميتوكوندريا',
                'category_en' => 'Cellular Longevity',
                'category_ar' => 'طول العمر الخلوي',
                'subcategory_en' => 'NAD+ Precursors',
                'subcategory_ar' => 'محفزات إنزيم NAD+',
                'brand' => 'Blue Zone Bioceuticals',
                'price' => 74.00,
                'sale_price' => 64.00,
                'is_featured' => true,
                'is_best_seller' => true,
                'is_new' => true,
                'status' => 'active',
                'rating' => 4.95,
                'reviews_count' => 189,
                'image' => '/assets/products/blue-cell.jpg',
                'images' => [
                    '/assets/products/blue-cell.jpg',
                ],
                'stock_online' => 96,
                'stock_offline' => 42,
                'low_stock_threshold' => 12,
                'short_description_en' => 'Comprehensive mitochondrial revitalizer engineered with pharmaceutical NMN and trans-resveratrol to replenish cellular NAD+ pools.',
                'short_description_ar' => 'مجدد حيوي شامل للميتوكوندريا الخلوية معزز بـ NMN فائق النقاء وريسفيراترول لتحفيز مستويات NAD+ في الجسم.',
                'description_en' => 'Formulated to target the primary hallmarks of biological aging. BLUE CELL optimizes mitochondrial energy synthesis, supports DNA repair enzyme PARP-1, and activates longevity sirtuin pathways.',
                'description_ar' => 'مطور لاستهداف الجذور الأساسية للشيخوخة البيولوجية. يعزز إنتاج الطاقة الخلوية، ويدعم إنزيمات إصلاح الحمض النووي PARP-1، وينشط مسارات السيرتوين.',
                'benefits_en' => [
                    'Elevates whole-blood NAD+ levels within 14 days of sustained intake',
                    'Potentiates mitochondrial biogenesis and cellular ATP replenishment',
                    'Protects genomic integrity against environmental oxidative stress',
                    'Promotes optimal sirtuin SIRT1 and SIRT3 enzymatic activation',
                ],
                'benefits_ar' => [
                    'يرفع مستويات NAD+ في الدم خلال 14 يوماً من الاستخدام المنتظم',
                    'يعزز التجدد الحيوي للميتوكوندريا وإنتاج طاقة ATP الخلوية',
                    'يحمي سلامة الجينوم والحمض النووي من التأكسد البيئي',
                    'ينشط بروتينات طول العمر SIRT1 و SIRT3 بكفاءة عالية',
                ],
                'usage_en' => 'Take 2 capsules in the morning fasting with a glass of water, or as clinically recommended.',
                'usage_ar' => 'تناول كبسولتين صباحاً على معدة خاوية مع كوب ماء نقي، أو حسب الإرشادات الإكلينيكية.',
                'dosage_en' => '2 Veg Capsules Daily',
                'dosage_ar' => 'كبسولتان نباتيتان يومياً',
                'package_size_en' => '60 Enteric Veg Capsules',
                'package_size_ar' => '60 كبسولة معوية نباتية',
                'target_audience_en' => 'Adults 30+ aiming to mitigate cellular senescence and optimize biological age.',
                'target_audience_ar' => 'البالغون فوق 30 عاماً الراغبون في استعادة الحيوية الخلوية وتحسين العمر البيولوجي.',
                'gender' => 'Unisex',
                'age_group' => '25+',
                'health_goal_en' => 'Anti-Aging, Cellular Energy, Mitochondrial Vitality',
                'health_goal_ar' => 'مكافحة الشيخوخة، طاقة الخلايا، حيوية الميتوكوندريا',
                'professional_info' => [
                    'clinical_mechanism' => 'Beta-Nicotinamide Mononucleotide is transported through the Slc12a8 carrier to rapidly phosphorylate into NAD+. Trans-resveratrol acts as an allosteric activator of SIRT1 deacetylase.',
                    'formula_details' => 'Beta-NMN 99.8% enzymatic grade, Micronized 99% Trans-Resveratrol, Apigenin (chamomile isolate), Quercetin Phytosome.',
                    'contraindications' => 'Contraindicated in active oncological therapy without oncologist pre-clearance. Not evaluated during pregnancy or lactation.',
                    'warnings' => 'Keep refrigerated after opening for maximal enzymatic longevity. Do not expose to temperatures exceeding 30°C.',
                    'interactions' => 'Synergistic with Metformin or Berberine in AMPK metabolic signaling.',
                ],
                'ingredients' => [
                    ['name_en' => 'Beta-NMN (99.8% Ultra-Pure)', 'name_ar' => 'بيتا NMN فائق النقاوة (99.8%)', 'dose' => '300 mg'],
                    ['name_en' => 'Micronized Trans-Resveratrol', 'name_ar' => 'ترانس ريسفيراترول دقيق الجزيئات', 'dose' => '150 mg'],
                    ['name_en' => 'Quercetin Phytosome', 'name_ar' => 'كيرسيتين فيتوسوم سريع الامتصاص', 'dose' => '100 mg'],
                    ['name_en' => 'Fisetin (Stem of Cotinus coggygria)', 'name_ar' => 'فيسيتين نقي من خلاصة الأشجار', 'dose' => '50 mg'],
                ],
                'variants' => [
                    [
                        'id' => 201,
                        'name_en' => '30-Day Cell Reserve (60 Capsules)',
                        'name_ar' => 'احتياطي خلايا 30 يوماً (60 كبسولة)',
                        'sku' => 'BZ-CEL-60C',
                        'price' => 74.00,
                        'stock_online' => 60,
                        'stock_offline' => 28,
                    ],
                    [
                        'id' => 202,
                        'name_en' => 'Quarterly Mitochondrial Protocol (180 Capsules)',
                        'name_ar' => 'بروتوكول الميتوكوندريا الفصلي (180 كبسولة)',
                        'sku' => 'BZ-CEL-180C',
                        'price' => 195.00,
                        'stock_online' => 36,
                        'stock_offline' => 14,
                    ],
                ],
            ],
            [
                'id' => 3,
                'slug' => 'blue-defense',
                'sku' => 'BZ-DEF-003',
                'barcode' => '628100091003',
                'name_en' => 'BLUE DEFENSE',
                'name_ar' => 'بلو ديفينس',
                'tagline_en' => 'Immune Resilience & Polyphenol Complex',
                'tagline_ar' => 'مناعة فائقة ومجمع البوليفينول الطبيعي',
                'category_en' => 'Immunity & Resilience',
                'category_ar' => 'المناعة والمرونة الحيوية',
                'subcategory_en' => 'Polyphenols',
                'subcategory_ar' => 'البوليفينول ومضادات الأكسدة',
                'brand' => 'Blue Zone Bioceuticals',
                'price' => 52.00,
                'sale_price' => 45.00,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'status' => 'active',
                'rating' => 4.85,
                'reviews_count' => 97,
                'image' => '/assets/products/blue-defense.jpg',
                'images' => [
                    '/assets/products/blue-defense.jpg',
                ],
                'stock_online' => 140,
                'stock_offline' => 55,
                'low_stock_threshold' => 20,
                'short_description_en' => 'Synergistic botanical defense matrix combining high-potency elderberry, olive leaf oleuropein, zinc glycinate, and bio-fermented vitamin C.',
                'short_description_ar' => 'مركب نباتي دفاعي متكامل يجمع بين خلاصة البيلسان، مستخلص أوراق الزيتون، زنك غليسينات، وفيتامين C المخمر حيوياً.',
                'description_en' => 'Formulated from the wild mountain botanicals of Sardinia and Greece. Strengthens upper respiratory defense barriers and supports innate immune cell chemotaxis.',
                'description_ar' => 'مستخلص من أعشاب جبال سردينيا واليونان البرية. يعزز حواجز الجهاز التنفسي ويدعم حركة خلايا المناعة الفطرية الطبيعية.',
                'benefits_en' => [
                    'Multi-tiered immune system reinforcement against seasonal challenges',
                    'Standardized 20% Oleuropein for cellular vascular defense',
                    'Chelated zinc with enhanced bioavailability without gastrointestinal discomfort',
                    'Powerful antioxidant scavenger reducing inflammatory biomarkers',
                ],
                'benefits_ar' => [
                    'تعزيز مناعي متعدد الطبقات لمواجهة تقلبات المواسم',
                    'خلاصة أوليوروبين موحدة بنسبة 20% لحماية الأوعية والخلايا',
                    'زنك مخلبي عالي الامتصاص لطيف على المعدة بدون إزعاج هضمي',
                    'مضاد أكسدة فائق يقلل مؤشرات الإجهاد التأكسدي والالتهابي',
                ],
                'usage_en' => 'Take 2 capsules daily with your midday meal.',
                'usage_ar' => 'تناول كبسولتين يومياً مع وجبة الغداء.',
                'dosage_en' => '2 Veg Capsules Daily',
                'dosage_ar' => 'كبسولتان نباتيتان يومياً',
                'package_size_en' => '60 Vegetable Capsules',
                'package_size_ar' => '60 كبسولة نباتية',
                'target_audience_en' => 'Anyone seeking year-round cellular immune fortification.',
                'target_audience_ar' => 'كل من يسعى لتحصين مناعي مستدام وحماية الخلايا على مدار العام.',
                'gender' => 'Unisex',
                'age_group' => '12+',
                'health_goal_en' => 'Immunity, Respiratory Health, Antioxidants',
                'health_goal_ar' => 'المناعة، الجهاز التنفسي، ومضادات الأكسدة',
                'professional_info' => [
                    'clinical_mechanism' => 'Inhibits viral neuraminidase activity via anthocyanidins. Enhances T-cell proliferation and neutralizes reactive nitrogen intermediates.',
                    'formula_details' => 'Sambucus Nigra Extract 64:1, Olea Europaea Leaf (20% Oleuropein), Zinc Bisglycinate Chelate (TRAACS), Acerola Berry Bio-Fermented Ascorbic Acid.',
                    'contraindications' => 'Use caution in autoimmune disorders such as Multiple Sclerosis, SLE, or Rheumatoid Arthritis without immunology consultation.',
                    'warnings' => 'Do not use as a substitute for acute antimicrobial clinical therapy.',
                    'interactions' => 'Avoid simultaneous calcium supplementation at the same hour to preserve zinc chelate uptake.',
                ],
                'ingredients' => [
                    ['name_en' => 'European Elderberry (Sambucus nigra)', 'name_ar' => 'خلاصة البيلسان الأوروبي المركز', 'dose' => '350 mg'],
                    ['name_en' => 'Olive Leaf Extract (20% Oleuropein)', 'name_ar' => 'مستخلص ورق الزيتون (20% أوليوروبين)', 'dose' => '200 mg'],
                    ['name_en' => 'Zinc Bisglycinate Chelate', 'name_ar' => 'زنك مخلبي فائق الامتصاص', 'dose' => '25 mg'],
                    ['name_en' => 'Acerola Cherry Bio-Vitamin C', 'name_ar' => 'فيتامين C طبيعي من كرز الأسيرولا', 'dose' => '180 mg'],
                ],
                'variants' => [
                    [
                        'id' => 301,
                        'name_en' => 'Standard Bottle (60 Capsules)',
                        'name_ar' => 'العبوة القياسية (60 كبسولة)',
                        'sku' => 'BZ-DEF-60C',
                        'price' => 52.00,
                        'stock_online' => 95,
                        'stock_offline' => 35,
                    ],
                ],
            ],
            [
                'id' => 4,
                'slug' => 'blue-metabolic',
                'sku' => 'BZ-MET-004',
                'barcode' => '628100091004',
                'name_en' => 'BLUE METABOLIC',
                'name_ar' => 'بلو ميتابوليك',
                'tagline_en' => 'AMPK Activator & Fasting Mimetic',
                'tagline_ar' => 'منشط مسار AMPK ومحاكي الصيام الصحي',
                'category_en' => 'Metabolic Health',
                'category_ar' => 'الأيض والصحة الاستقلابية',
                'subcategory_en' => 'Glucose Regulation',
                'subcategory_ar' => 'تنظيم سكر الدم والأنسولين',
                'brand' => 'Blue Zone Bioceuticals',
                'price' => 59.00,
                'sale_price' => 52.00,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => true,
                'status' => 'active',
                'rating' => 4.9,
                'reviews_count' => 84,
                'image' => '/assets/products/blue-metabolic.jpg',
                'images' => [
                    '/assets/products/blue-metabolic.jpg',
                ],
                'stock_online' => 80,
                'stock_offline' => 25,
                'low_stock_threshold' => 10,
                'short_description_en' => 'Cellular metabolic modulator mimicking the benefits of caloric restriction and intermittent fasting through direct AMPK pathway activation.',
                'short_description_ar' => 'معدل أيض خلوي يحاكي فوائد الصيام المتقطع والتحكم الحراري عبر تنشيط مسار إنزيم AMPK المركزي.',
                'description_en' => 'Formulated with Berberine phytosome, Ceylon cinnamon bark extract, and Chromium picolinate to optimize postprandial glucose sensitivity and hepatic lipid transport.',
                'description_ar' => 'يحتوي على البربرين الفيتوسومي وخلاصة قرفة سيلان والكروميوم بيكولينات لدعم توازن سكر الدم بعد الوجبات وتحفيز حرق الدهون الخلوية.',
                'benefits_en' => [
                    'Supports healthy fasting glucose and HbA1c in normal ranges',
                    'Activates cellular autophagy and fat oxidation pathways',
                    'Curbs sugar cravings and mid-afternoon energy crashes',
                    'Improves gut microbiome composition favoring Akkermansia muciniphila',
                ],
                'benefits_ar' => [
                    'يدعم توازن مستويات السكر ومؤشر التراكمي ضمن الحدود الطبيعية',
                    'يحفز عملية الالتهام الذاتي الخلوي Autophagy وأكسدة الدهون',
                    'يقلل من الرغبة الشديدة في تناول السكريات وهبوط الطاقة المفاجئ',
                    'يدعم بكتيريا الأمعاء النافعة المسؤولة عن سلامة الغشاء المعوي',
                ],
                'usage_en' => 'Take 1 capsule 15 minutes before your two largest carbohydrate-containing meals.',
                'usage_ar' => 'تناول كبسولة واحدة قبل 15 دقيقة من أكبر وجبتين تحتويان على الكربوهيدرات.',
                'dosage_en' => '2 Veg Capsules Daily',
                'dosage_ar' => 'كبسولتان نباتيتان يومياً',
                'package_size_en' => '60 Gastro-Resistant Capsules',
                'package_size_ar' => '60 كبسولة مقاومة لحمض المعدة',
                'target_audience_en' => 'Individuals focused on body composition, metabolic fitness, and glucose resilience.',
                'target_audience_ar' => 'المهتمون بلياقة الأيض، تنظيم سكر الدم، وتحسين الكتلة الحيوية للجسم.',
                'gender' => 'Unisex',
                'age_group' => '18+',
                'health_goal_en' => 'Metabolism, Glucose Control, Weight Wellness',
                'health_goal_ar' => 'الأيض، تنظيم السكر، والرشاقة الحيوية',
                'professional_info' => [
                    'clinical_mechanism' => 'Berberine phosphorylates AMPK via liver kinase B1 (LKB1), stimulating GLUT4 transporter translocation to skeletal muscle membrane.',
                    'formula_details' => 'Berberine HCl (Berbevis phospholipid matrix, 9.6x bioavailability), Cinnamomum Verum 10:1 water extract, Chromium Picolinate.',
                    'contraindications' => 'Concomitant use with prescription antidiabetic sulfonylureas or insulin requires strict blood sugar titration to prevent hypoglycemia.',
                    'warnings' => 'Discontinue use 2 weeks prior to scheduled surgical interventions.',
                    'interactions' => 'Interacts with CYP3A4 substrate pharmaceuticals.',
                ],
                'ingredients' => [
                    ['name_en' => 'Berbevis Berberine Phytosome', 'name_ar' => 'بربرين فيتوسومي عالي الامتصاص', 'dose' => '550 mg'],
                    ['name_en' => 'True Ceylon Cinnamon Extract', 'name_ar' => 'خلاصة قرفة سيلان النقية الأصلية', 'dose' => '200 mg'],
                    ['name_en' => 'Chromium Picolinate', 'name_ar' => 'كروميوم بيكولينات', 'dose' => '200 mcg'],
                    ['name_en' => 'Alpha Lipoic Acid (R-Form)', 'name_ar' => 'حمض ألفا ليبويك (الصيغة الفعالة R)', 'dose' => '150 mg'],
                ],
                'variants' => [
                    [
                        'id' => 401,
                        'name_en' => 'Standard Metabolic Bottle (60 Capsules)',
                        'name_ar' => 'العبوة القياسية (60 كبسولة)',
                        'sku' => 'BZ-MET-60C',
                        'price' => 59.00,
                        'stock_online' => 55,
                        'stock_offline' => 15,
                    ],
                ],
            ],
            [
                'id' => 5,
                'slug' => 'blue-sleep',
                'sku' => 'BZ-SLP-005',
                'barcode' => '628100091005',
                'name_en' => 'BLUE SLEEP',
                'name_ar' => 'بلو سليب',
                'tagline_en' => 'Deep Stage REM & Circadian Re-alignment',
                'tagline_ar' => 'نوم عميق وإعادة ضبط الساعة البيولوجية',
                'category_en' => 'Sleep & Recovery',
                'category_ar' => 'النوم والاستشفاء الخلوي',
                'subcategory_en' => 'Circadian Optimization',
                'subcategory_ar' => 'تنظيم الإيقاع اليومي',
                'brand' => 'Blue Zone Bioceuticals',
                'price' => 48.00,
                'sale_price' => 42.00,
                'is_featured' => false,
                'is_best_seller' => true,
                'is_new' => false,
                'status' => 'active',
                'rating' => 4.92,
                'reviews_count' => 165,
                'image' => '/assets/products/blue-sleep.jpg',
                'images' => [
                    '/assets/products/blue-sleep.jpg',
                ],
                'stock_online' => 110,
                'stock_offline' => 45,
                'low_stock_threshold' => 15,
                'short_description_en' => 'Non-habit forming botanical and mineral elixir promoting delta-wave slow sleep, muscular relaxation, and nocturnal glymphatic brain detox.',
                'short_description_ar' => 'مركب نباتي ومعدني مهدئ غير مسبب للاعتياد، يعزز موجات دلتا العميقة، استرخاء العضلات، وإزالة السموم الدماغية ليلاً.',
                'description_en' => 'Combining micro-dosed magnesium bisglycinate with L-theanine, tart cherry melatonin precursors, and chamomile apigenin for serene restorative sleep.',
                'description_ar' => 'مزيج مدروس من مغنيسيوم بيسغليسينات مع إل-ثيانين وخلاصة الكرز الحامض الغنية بالميلاتونين الطبيعي وأبيجينين البابونج.',
                'benefits_en' => [
                    'Reduces sleep latency (time to fall asleep) naturally',
                    'Increases duration of Stage 3 slow-wave deep sleep and REM cycles',
                    'Wake up refreshed with zero morning grogginess or fog',
                    'Soothes muscular twitching and nocturnal tension with chelated magnesium',
                ],
                'benefits_ar' => [
                    'يقلل الوقت المستغرق للاستغراق في النوم بشكل طبيعي وسلس',
                    'يطيل فترات النوم العميق واستعادة التوازن العصبي ومرحلة REM',
                    'استيقاظ بنشاط وصفاء ذهني دون خمول أو تشويش صباحي',
                    'يهدئ التشنجات العضلية والتوتر العصبي بمغنيسيوم مخلبي نقي',
                ],
                'usage_en' => 'Take 2 capsules 45 minutes prior to sleep with a warm caffeine-free herbal infusion.',
                'usage_ar' => 'تناول كبسولتين قبل النوم بـ 45 دقيقة مع كوب من منقوع الأعشاب الدافئ الخالي من الكافيين.',
                'dosage_en' => '2 Veg Capsules Nightly',
                'dosage_ar' => 'كبسولتان نباتيتان مساءً',
                'package_size_en' => '60 Capsules (30 Nights)',
                'package_size_ar' => '60 كبسولة (تكفي 30 ليلة)',
                'target_audience_en' => 'High-stress executives, shift workers, and light sleepers needing deep restorative rest.',
                'target_audience_ar' => 'أصحاب الأعمال، وأصحاب التحديات الذهنية، ومن يعانون من تقطع النوم والأرق.',
                'gender' => 'Unisex',
                'age_group' => '18+',
                'health_goal_en' => 'Sleep Quality, Stress Reduction, Recovery',
                'health_goal_ar' => 'جودة النوم، تقليل التوتر، والاستشفاء',
                'professional_info' => [
                    'clinical_mechanism' => 'L-Theanine crosses blood-brain barrier to bind to glutamate receptors, boosting inhibitory neurotransmitter GABA. Tart cherry provides bio-identical phytonutrient melatonin fractions.',
                    'formula_details' => 'Magnesium Bisglycinate (TRAACS), Suntheanine pure L-theanine, Montmorency Tart Cherry 50:1, Apigenin 98%.',
                    'contraindications' => 'Do not drive, operate heavy machinery, or consume concurrent central nervous system sedatives.',
                    'warnings' => 'Consult clinician if pregnant or suffering from sleep apnea.',
                    'interactions' => 'Potentiates effects of benzodiazepines and sedative antihistamines.',
                ],
                'ingredients' => [
                    ['name_en' => 'Magnesium Bisglycinate (TRAACS)', 'name_ar' => 'مغنيسيوم بيسغليسينات مخلبي', 'dose' => '200 mg elemental'],
                    ['name_en' => 'Suntheanine L-Theanine', 'name_ar' => 'إل-ثيانين نقي مسجل (Suntheanine)', 'dose' => '200 mg'],
                    ['name_en' => 'Montmorency Tart Cherry Extract', 'name_ar' => 'خلاصة كرز مونتمورنسي الحامض', 'dose' => '300 mg'],
                    ['name_en' => 'Chamomile Flower Apigenin', 'name_ar' => 'أبيجينين زهور البابونج المهدئ', 'dose' => '50 mg'],
                ],
                'variants' => [
                    [
                        'id' => 501,
                        'name_en' => '30 Nights Slumber Pack (60 Capsules)',
                        'name_ar' => 'عبوة 30 ليلة نوم هانئ (60 كبسولة)',
                        'sku' => 'BZ-SLP-60C',
                        'price' => 48.00,
                        'stock_online' => 75,
                        'stock_offline' => 30,
                    ],
                ],
            ],
            [
                'id' => 6,
                'slug' => 'blue-vitality',
                'sku' => 'BZ-VIT-006',
                'barcode' => '628100091006',
                'name_en' => 'BLUE VITALITY',
                'name_ar' => 'بلو فايتاليتي',
                'tagline_en' => 'Cardiovascular Longevity & Endothelial Health',
                'tagline_ar' => 'طول عمر القلب وصحة الأوعية الدموية',
                'category_en' => 'Cardiovascular Health',
                'category_ar' => 'صحة القلب والأوعية',
                'subcategory_en' => 'Nitric Oxide & Lipids',
                'subcategory_ar' => 'أكسيد النيتريك وتوازن الدهون',
                'brand' => 'Blue Zone Bioceuticals',
                'price' => 62.00,
                'sale_price' => 54.00,
                'is_featured' => true,
                'is_best_seller' => false,
                'is_new' => false,
                'status' => 'active',
                'rating' => 4.88,
                'reviews_count' => 112,
                'image' => '/assets/products/blue-vitality.jpg',
                'images' => [
                    '/assets/products/blue-vitality.jpg',
                ],
                'stock_online' => 65,
                'stock_offline' => 20,
                'low_stock_threshold' => 12,
                'short_description_en' => 'Advanced endothelial formula enhancing nitric oxide production, arterial compliance, and cellular microvascular flow.',
                'short_description_ar' => 'تركيبة بطانية متقدمة ترفع إنتاج أكسيد النيتريك وتعزز مرونة الشرايين والتروية الدموية الدقيقة.',
                'description_en' => 'Formulated from French Maritime Pine Bark extract, fermented beetroot nitrates, and MenaQ7 natural vitamin K2 to promote youthful arterial elasticity.',
                'description_ar' => 'مستخلص من لحاء الصنوبر البحري الفرنسي ونترات الشمندر المخمر مع فيتامين K2 الطبيعي لتعزيز مرونة الشرايين وصحة القلب.',
                'benefits_en' => [
                    'Stimulates endothelial Nitric Oxide Synthase (eNOS) for healthy circulation',
                    'Assists arterial flexibility and healthy blood pressure within normal range',
                    'Directs calcium away from soft arterial walls into bone matrix via Vitamin K2',
                    'Boosts physical endurance and cellular oxygen delivery',
                ],
                'benefits_ar' => [
                    'يحفز إنزيم eNOS الطبيعي لتعزيز تدفق الدم الصحي لجميع الأعضاء',
                    'يدعم مرونة الشرايين والحفاظ على ضغط دم متوازن ومثالي',
                    'يوجه الكالسيوم نحو العظام ويبعده عن التكلس في جدران الشرايين',
                    'يرفع طاقة التحمل العضلي والتروية بالأكسجين أثناء النشاط',
                ],
                'usage_en' => 'Take 2 capsules daily with breakfast.',
                'usage_ar' => 'تناول كبسولتين يومياً مع وجبة الإفطار.',
                'dosage_en' => '2 Veg Capsules Daily',
                'dosage_ar' => 'كبسولتان نباتيتان يومياً',
                'package_size_en' => '60 Capsules',
                'package_size_ar' => '60 كبسولة نباتية',
                'target_audience_en' => 'Individuals committed to lifelong cardiovascular vitality and athletic oxygen capacity.',
                'target_audience_ar' => 'المهتمون بصحة القلب والأوعية الدموية وقوة التحمل الرياضي طويل الأمد.',
                'gender' => 'Unisex',
                'age_group' => '25+',
                'health_goal_en' => 'Heart Health, Circulation, Endurance',
                'health_goal_ar' => 'صحة القلب، الدورة الدموية، واللياقة البدنية',
                'professional_info' => [
                    'clinical_mechanism' => 'Pycnogenol activates endothelial nitric oxide synthase and reduces vascular endothelin-1. MenaQ7 carboxylates matrix Gla protein (MGP) preventing arterial calcification.',
                    'formula_details' => 'Standardized French Maritime Pine Bark Extract (65-75% procyanidins), Red Beetroot (10% nitrates), MenaQ7 Vitamin K2 (as MK-7) 180 mcg.',
                    'contraindications' => 'Consult cardiologist if taking prescription nitrates or antihypertensive medications.',
                    'warnings' => 'Do not combine with PDE-5 inhibitors without medical consent.',
                    'interactions' => 'Synergistic with high-purity Omega-3 fatty acids.',
                ],
                'ingredients' => [
                    ['name_en' => 'Maritime Pine Bark Extract (Pycnogenol)', 'name_ar' => 'مستخلص لحاء الصنوبر البحري الفرنسي', 'dose' => '100 mg'],
                    ['name_en' => 'Fermented Red Beet Nitrate Matrix', 'name_ar' => 'مصفوفة نترات الشمندر الأحمر المخمر', 'dose' => '400 mg'],
                    ['name_en' => 'MenaQ7 Natural Vitamin K2 (MK-7)', 'name_ar' => 'فيتامين K2 الطبيعي النقي (ميناكيو 7)', 'dose' => '180 mcg'],
                    ['name_en' => 'BioPerine Black Pepper Extract', 'name_ar' => 'بيوبيرين لتعزيز التوافر الحيوي', 'dose' => '5 mg'],
                ],
                'variants' => [
                    [
                        'id' => 601,
                        'name_en' => 'Standard Vitality Bottle (60 Capsules)',
                        'name_ar' => 'العبوة القياسية (60 كبسولة)',
                        'sku' => 'BZ-VIT-60C',
                        'price' => 62.00,
                        'stock_online' => 45,
                        'stock_offline' => 15,
                    ],
                ],
            ],
        ];
    }

    /**
     * Find product by slug or id.
     *
     * @param string|int $identifier
     * @return array<string, mixed>|null
     */
    public static function find(string|int $identifier): ?array
    {
        $products = self::all();
        foreach ($products as $p) {
            if ($p['slug'] === (string)$identifier || $p['id'] === (int)$identifier) {
                return $p;
            }
        }
        return null;
    }
}
